"""Real Sacramento County inspection report text, extracted with pypdf while
planning the lead scraper (docs/lead-scraper-plan.md) and trimmed to the
header plus the first violation block. Used by test_leads_classify.py and
test_leads_reports.py so those tests run against real report formatting
instead of hand-typed approximations."""

# NATOMAS FOOD & LIQUOR, 2026-09-02: rodent droppings, no pest-control invoice on site.
NATOMAS = 'Entered Date09/02/2026\nPag1\nHeader\nRetail Food Facility\nOwners NameSUPER SHOT RAJPURA INCEst NameNATOMAS FOOD & LIQUOR\nCitySacramentoAddress4000 E Commerce Way Zip95834 Phone(916) 416-1664\nFAFA0044262 Permit IDPR0091055 PurposeINSPECTION\nProg Identifier- PE: 1612 CT: 70.28\nIteration Violation23.VERMIN AND ANIMAL CONTAMINATION\nObservations: MAJOR VIOLATION: \n-Hundreds of rodent droppings are observed on the counter space below the Red Bull, deli sandwich/burrito \nmerchandisers and Frazil unit. \n-200+ rodent droppings are on the bottom of the cabinet stored with cases of Frazil mix below the counter.\nRemove all units and cased products from affected areas. Remove all droppings and clean/sanitize all areas immediately. \nPer employee, pest control service invoice could not be located. Temporarily correcting by beginning work on areas.\nProvide licensed pest control service as needed. Evaluate and assess building to eliminate harborage and entrance points \nwithin 7 days.\nA reinspection may be conducted to verify pest control management. Fee of $201 may apply. \nCode Description: A food facility shall at all times be equipped, maintained, and operated as to prevent the entrance and \nharborage of animals, birds, and vermin, including, but not limited to rodents and insects. Service animals as defined in \nsection 113903 may be permitted in areas that are not used for food preparation and that are usually open for consumers \nif a health or safety hazard will not result from the presence\n32a.FOOD PRESENTATION AND LABELING\nObservations: Store bagged ice are missing name and place of manufacture.'

# SEAPOT, 2026-09-01: German cockroach closure, no phone in the header (verified live).
SEAPOT = 'Entered Date09/01/2026\nPag1\nHeader\nRetail Food Facility\nOwners NameKHP SACRAMENTO LLCEst NameSEAPOT\nCitySacramentoAddress6009 Florin Rd Zip95823 Phone\nFAFA0046536 Permit IDPR153179 PurposeINSPECTION\nProg Identifier- PE: 1621 CT: 47.01\nIteration Violation23.VERMIN AND ANIMAL CONTAMINATION\nObservations: MAJOR VIOLATION - CLOSURE: Observed the following vermin activity: \n- Approximately 4 to 5 adult live German cockroaches located under the automatic dishwasher along back leg post. \n- 2 to 3 adult live German cockroaches in the automatic dishwasher along electrical conduit lines. \n- 1 adult female German cockroach with egg located below the automatic dishwasher along the motor. \n- 2 German cockroach nymphs located below the automatic dishwasher along the motor.\n- Observed 1 live adult German cockroach behind the preparation sink located at the rear of the kitchen. \n- Found several dead cockroach bodies on the floor under the automatic dishwasher. \nDue to evidence of a vermin infestation, facility is hereby closed. No food sales or preparation is permitted until facility is \nreinspected and approved to open by the Environmental Management Department (EMD).\nIn order to reopen:\n- Highly recommend providing aggressive professional pest control to eliminate vermin infestation using approved pest \ncontrol methods. \n- Clean and sanitize all food contact and food preparation areas.\nOnce facility is ready for a reinspection, contact EMD to schedule an appointment: (916) 875-8440. \n35.EQUIPMENT APPROVED AND MAINTAINED\nObservations: table top fryer observed on prep table.'

# KFC/A&W #181, 2026-08-31: hot/cold holding (page 1), cockroach + fly on a later page
# (this excerpt is page 1, which has NO vermin block -- used as a "no signal" case for
# the classifier even though the live facility did have one elsewhere in the report).
KFC_AW_PAGE1 = "Entered Date08/31/2026\nPag1\nHeader\nRetail Food Facility\nOwners NameJ-285 INCEst NameKFC/ A&W #181\nCitySacramentoAddress8335 Elk Grove Florin Rd Zip95829 Phone(916) 525-3600\nFAFA0028458 Permit IDPR0052807 PurposeINSPECTION\nProg Identifier- PE: 1622 CT: 93.12\nIteration Violation7.HOT AND COLD HOLDING TEMPERATURES\nObservations: The following potentially hazardous foods (PHFs) were observed out of proper holding temperature:\nMAJOR VIOLATION:\nMeasured in ready-to-eat walk-in cooler:\n-shredded cheese at 53F\nDiscarded at time of inspection. See violation #35 for further details.\n45.FLOOR, WALL, AND CEILING FINISHES\nObservations: minor repair needed."

# KFC/A&W #181: the actual vermin block from later in the same report (live cockroach
# found under dry storage, plus a fly -- confirmed live as "cockroach" label since
# cockroach evidence outranks a lone fly mention).
KFC_AW_VERMIN = "Iteration Violation23.VERMIN AND ANIMAL CONTAMINATION\nObservations: MAJOR VIOLATION: Live adult German cockroach found under dry storage by grease trap and floor sink. \nEliminated by staff at time of inspection.\nMINOR VIOLATION: Fly hovering in dry storage area. Eliminate within 3 days.\nCode Description: A food facility shall at all times be equipped, maintained, and operated as to prevent the entrance and \nharborage of animals, birds, and vermin.\n40.WIPING CLOTHS STORAGE AND USE\nObservations: bucket of wiping cloths under prep line."

# CURRIES & BIRYANIS, 2026-08-29: German cockroach closure, phone present, inspector
# recommends sealing gaps/crevices (an exclusion, not a rodent, pest).
CURRIES = 'Entered Date08/29/2026\nPag1\nHeader\nRetail Food Facility\nOwners NameH & D DUO LLCEst NameCURRIES & BIRYANIS\nCityFolsomAddress157 Iron Point Rd Zip95630 Phone(516) 567-1898\nFAFA0004295 Permit IDPR152676 PurposeREINSPECTION\nProg Identifier- PE: 1622 CT: 85.04\nIteration Violation23.VERMIN AND ANIMAL CONTAMINATION\nObservations: MAJOR VIOLATION - CLOSURE: Vermin activity: \nObserved activity:\n2 adult live German cockroaches located under prepsink between wall and prep sink backsplash plate.\n2 live nymphs on floor below prep sink. Eliminated during inspection.\n1 live nymph on floor under kitchen prep table.\n1 juvenile, 1 adult activity on the underside of kitchen prep table.\n3 live adult under 3 compartment sink between wall and 3 compartment backsplash plate.\n2 eggs on floor. Eliminated during inspection.\nHighly recommend:\n1) Move all equipment away from wall. Seal all gaps and crevices, gaps in drain collars, crevices under both prep sink, 3 \ncompartment sinks and storage walk in freezer floor (raw, deteriorated wood)\n2) Place new glue traps to trap and identify area of activity.\n3) Self inspect with a flashlight.\n4) Continue aggressive pest control in areas of observed activity. Pest control was reviewed, service conducted 8/28/26. \nDue to evidence of a vermin infestation, facility is hereby closed. \n45.FLOOR, WALL, AND CEILING FINISHES\nObservations: minor wall repair needed.'

# DIVINE PACIFIC FOODS, 2026-09-01: cockroach + ants, has an existing pest-control
# contact ("email proof of pest control service") -- has_pco should read True here.
DIVINE = "Entered Date09/01/2026\nPag1\nHeader\nRetail Food Facility\nOwners NamePOASA KOROITAMANAEst NameDIVINE PACIFIC FOODS\nCitySacramentoAddress7298 Franklin Blvd Ste F Zip95823 Phone(916) 391-8933\nFAFA0003464 Permit IDPR0003751 PurposeINSPECTION\nProg Identifier- PE: 1612 CT: 49.08\nIteration Violation23.VERMIN AND ANIMAL CONTAMINATION\nObservations: MAJOR VIOLATION: Observed the following vermin activity: \n-1 live adult German cockroach inside hand soap dispenser.\n-1 live adult German cockroach observed to be crawling into crevice at tile above handwash sink.\n-5 dead nymph and 3 dead/dying adult German cockroaches at glue trap below electrical box.\nNo vermin activity observed in the front retail area of facility. Facility may not prepare or sell any non-prepackaged food \nitems, but may continue to sell items in original manufacturer sealed containers. \nDue to evidence of a vermin infestation, facility is suspended of open food activities (raw meat slicing, etc.). Remove all \nroaches, clean area, and email proof of pest control service to mataj@saccounty.gov. A reinspection may be conducted \nwithin 24 hours to ensure compliance. \nSupervisor Consulted: S. LePage\nMinor Violation:\nObserved several live ants crawling against wall around warewash/food prep area. Facility shall be vermin free at all times. \n35.EQUIPMENT APPROVED AND MAINTAINED\nObservations: walk-in cooler inoperable."

# FOOD 4 LESS #16, 2026-08-24: fly pupae only, no rodent/cockroach language at all.
FOOD4LESS = "Entered Date08/24/2026\nPag1\nHeader\nRetail Food Facility\nOwners NamePAQ INCEst NameFOOD 4 LESS #16\nCitySacramentoAddress3547 Bradshaw Rd Zip95827 Phone(916) 854-4524\nFAFA0013249 Permit IDPR0137567 PurposeINSPECTION\nProg IdentifierKITCHEN - PE: 1622 CT: 90.05\nIteration Violation7.HOT AND COLD HOLDING TEMPERATURES\nObservations: MAJOR VIOLATION:\nHorchata measured at 61F. Corrected on site. \nCode Description: Potentially hazardous foods shall be maintained at or below 41F.\n23.VERMIN AND ANIMAL CONTAMINATION\nObservations: MAJOR VIOLATION:\nIn the back corner near the clear curtains beside the large mixing machine, an unused steel sheet, that resembled a range \nhood, was covered with at least 120 fly pupa. Some pupa have hatched, most had not hatched. Operator was instructed to \nremove the pupa filled sheet, pull all equipment from the corner, clean, and sanitize the area. \nLocated near the pupa were at least 4 adult flies. Remove flies within 24 hours. \nCode Description: A food facility shall at all times be equipped, maintained, and operated as to prevent vermin.\n14a.FOOD CONTACT SURFACES CLEANED AND SANITIZED\nObservations: dirty knives stored on the magnetic strip."

# BUD'S BUFFET, 2026-07-29: no VERMIN section at all (hot/cold holding, handwashing,
# etc.) -- the "no signal" / person-owner header case.
BUDS_NO_VERMIN = "Entered Date07/29/2026\nPag1\nHeader\nRetail Food Facility\nOwners NameHAROON KHANEst NameBUD'S BUFFET\nCitySacramentoAddress1016 10th St Zip95814 Phone(510) 376-3395\nFAFA0001006 Permit IDPR160370 PurposeINSPECTION\nProg Identifier- PE: 1622 CT: 11.03\nIteration Violation7.HOT AND COLD HOLDING TEMPERATURES\nObservations: Grilled chicken at 117F. Voluntarily discarded at time of inspection. \nCode Description: Potentially hazardous foods shall be maintained at or below 41F or at or above 135F.\n1b.FOOD SAFETY CERTIFICATION\nObservations: Facility lacks an employee with a valid food manager certificate."

# AM/PM MINI MARKET #5731, West Sacramento, 2026-07-08 (Yolo County's own report
# template -- different layout from Sacramento's, no per-violation VERMIN block, a
# single page). Extracted live via pypdf from the real cached report, 2026-09-08 --
# confirms the facility-ID label is a single "Facility ID", not doubled the way
# Sacramento's "FAFA..." is, and that the PIC email repeats as a fallback source.
YOLO_AMPM = (
    "Total \nMAJ1\nCategoryRisk Category 2\nEstablishment NameAM/PM MINI MARKET #5731- FOOD "
    "Time Out09:15 AM Date07/08/2026Time In09:00 AM\nEstablishment CityWEST SACRAMENTO "
    "Establishment ZipCAEstablishment Address805 REED AVE\nPermit HolderAM/PM MINI MARKET "
    "#5731- FOOD Email addressreedaveampm@gmail.com Phone\nFacility IDFA0002270 PR IDPR0022221 "
    "Follow-up\nNotesCOMMENTS:\nThis is a follow up to the routine inspection conducted on "
    "7/7/26. The following has been corrected: \nThe ice machine is observed clean. Facility is "
    "okay to package ice for sale.\nReinspection Date On or After\nEnvironmental Health "
    "Specialist Emailboua.ly@yolocounty.govEnvironmental Health SpecialistBoua Ly\nPIC "
    "Sign\nPIC Emailreedaveampm@gmail.comAccepted By:"
)
